# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-21 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20160918_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='words_count',
            field=models.IntegerField(default=0),
        ),
    ]
