# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-22 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_words_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='test',
            field=models.BooleanField(default=False),
        ),
    ]
